### ISSUE TITLE
a little naming problem

### ISSUE THREAD

**Issue by wangxinghust** [MiracleYoung/You-are-Pythonista#32]
You-are-Pythonista/PythonExercise/Tool/Mini_Crawl/crawl_163playlist.py

in line 9, `javacript:void(0)`, a little naming problem. There is an 's' missing. There should be modified to `javascript:void(0)`.

Because it's misnamed, the program does not end automatically, even if the results are correct.

**Comment by MiracleYoung** [comment]
wow! thanks a lot !

**Comment by MiracleYoung** [comment]
Fixed
